name: Weekly Item Scraper

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run scraping script
        run: npm run fetch

      - name: Build pages
        run: npm run build

      - name: Commit and push updates
        run: |
          git config user.name Muut Moku
          git config user.email mokumoku.ukabu@gmail.com
          git add .
          git commit -m "Weekly update: $(date -u '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git
          git push origin HEAD:main
